@extends('layouts.accounting', ['pageTitle' => 'Cash & Bank', 'activePage' => 'cash-bank'])

@section('content')
@php($canManage = $demoCan('cash_bank.manage'))
<main id="cash-bank-page" class="p-4 sm:p-5"
    data-account-url="{{ route('cash-bank.accounts.store') }}"
    data-account-update-url="{{ route('cash-bank.accounts.update', ['code' => '__CODE__']) }}"
    data-account-status-url="{{ route('cash-bank.accounts.status', ['code' => '__CODE__']) }}"
    data-adjust-url="{{ route('cash-bank.accounts.adjust', ['code' => '__CODE__']) }}"
    data-activity-url="{{ route('cash-bank.accounts.activity', ['code' => '__CODE__']) }}"
    data-transaction-url="{{ route('cash-bank.transactions.store') }}"
    data-reverse-url="{{ route('cash-bank.transactions.reverse', ['identifier' => '__ID__']) }}"
    data-reconciliation-url="{{ route('cash-bank.reconciliations.store') }}"
    data-export-url="{{ route('cash-bank.export.csv') }}"
    data-chart-url="{{ route('chart-of-accounts') }}"
    data-user-role="{{ $user['role'] }}">
    <div class="dashboard-enter">
        <nav aria-label="Breadcrumb" class="flex items-center gap-2 text-xs text-slate-500"><span>Banking</span><span class="text-slate-300">/</span><span class="font-medium text-slate-700">Cash &amp; Bank</span></nav>
        <div class="mt-4 flex flex-col gap-3 xl:flex-row xl:items-start xl:justify-between">
            <div><h1 class="text-xl font-bold text-slate-900">Cash &amp; Bank</h1><p class="mt-1 text-xs text-slate-500">Posted cash activity, controlled adjustments, transfers, and reconciliation.</p></div>
            <div class="flex flex-wrap gap-2 print:hidden" aria-label="Cash and bank actions">
                @foreach ([['deposit', 'fa-plus', 'Deposit'], ['withdrawal', 'fa-minus', 'Withdrawal'], ['charge', 'fa-receipt', 'Bank Charge'], ['interest', 'fa-percent', 'Interest']] as [$type, $icon, $label])
                    <button type="button" class="apm-outline-button" data-open-transaction="{{ $type }}" @disabled(! $canManage) title="{{ $canManage ? $label : 'Only Administrators and Accountants can post transactions.' }}"><i class="fa-solid {{ $icon }} mr-1"></i>{{ $label }}</button>
                @endforeach
                <button type="button" class="apm-primary-button" data-open-transaction="transfer" @disabled(! $canManage) title="{{ $canManage ? 'Transfer funds' : 'Only Administrators and Accountants can post transfers.' }}"><i class="fa-solid fa-arrow-right-arrow-left"></i>Transfer</button>
            </div>
        </div>

        <section class="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4" aria-label="Cash summary">
            <article class="apm-summary-card"><p>Total Cash &amp; Bank</p><strong>&#8369;{{ number_format((float) $metrics['total'], 2) }}</strong><span>{{ count($activeCashAccounts) }} active accounts</span></article>
            <article class="apm-summary-card"><p>Bank Accounts</p><strong>{{ $metrics['bank_count'] }}</strong><span>Active bank accounts</span></article>
            <article class="apm-summary-card"><p>Total Inflows</p><strong class="!text-emerald-600">&#8369;{{ number_format((float) $metrics['inflow'], 2) }}</strong><span>Posted deposits and interest</span></article>
            <article class="apm-summary-card"><p>Total Outflows</p><strong class="!text-rose-600">&#8369;{{ number_format((float) $metrics['outflow'], 2) }}</strong><span>Posted withdrawals and charges</span></article>
        </section>

        <div class="mt-5 flex gap-1 overflow-x-auto border-b border-slate-200" role="tablist">
            <button class="apm-tab border-blue-600 text-blue-600" data-cb-tab="accounts" role="tab" aria-selected="true">Accounts</button>
            <button class="apm-tab" data-cb-tab="transactions" role="tab" aria-selected="false">Transactions</button>
            <button class="apm-tab" data-cb-tab="reconciliation" role="tab" aria-selected="false">Reconciliation</button>
        </div>

        <section class="mt-4" data-cb-panel="accounts">
            <div class="mb-3 flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
                <p class="text-xs text-slate-500"><i class="fa-solid fa-circle-info mr-1 text-blue-500"></i>Balances change only through posted entries, reversals, or controlled adjustments.</p>
                <button id="cb-add-account" type="button" class="apm-outline-button self-start print:hidden" @disabled(! $canManage)><i class="fa-solid fa-plus mr-1"></i>Add Account</button>
            </div>
            <div id="cb-account-cards" class="grid gap-3 md:grid-cols-2 xl:grid-cols-3"></div>
        </section>

        <section class="mt-4 hidden" data-cb-panel="transactions">
            <div class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">
                <header class="flex flex-col gap-3 border-b border-slate-200 p-4 xl:flex-row xl:items-end">
                    <label class="relative flex-1"><span class="mb-1 block text-[10px] font-semibold uppercase text-slate-500">Search</span><i class="fa-solid fa-magnifying-glass absolute bottom-3 left-3 text-xs text-slate-400"></i><input id="cb-search" type="search" class="h-9 w-full rounded-lg border border-slate-200 pl-9 pr-3 text-xs" placeholder="Reference, journal, source, or description"></label>
                    <label class="text-[10px] font-semibold uppercase text-slate-500">Account<select id="cb-account-filter" class="mt-1 block h-9 min-w-40 rounded-lg border border-slate-200 px-3 text-xs font-normal normal-case"><option value="">All accounts</option>@foreach($cashAccounts as $account)<option value="{{ $account['code'] }}">{{ $account['code'] }} · {{ $account['name'] }}</option>@endforeach</select></label>
                    <label class="text-[10px] font-semibold uppercase text-slate-500">Type<select id="cb-type-filter" class="mt-1 block h-9 rounded-lg border border-slate-200 px-3 text-xs font-normal normal-case"><option value="">All types</option><option value="deposit">Deposit</option><option value="withdrawal">Withdrawal</option><option value="transfer">Transfer</option><option value="charge">Bank charge</option><option value="interest">Interest</option><option value="adjustment">Adjustment</option><option value="reversal">Reversal</option></select></label>
                    <label class="text-[10px] font-semibold uppercase text-slate-500">Status<select id="cb-status-filter" class="mt-1 block h-9 rounded-lg border border-slate-200 px-3 text-xs font-normal normal-case"><option value="">All status</option><option>Uncleared</option><option>Cleared</option><option>Reversed</option></select></label>
                    <label class="text-[10px] font-semibold uppercase text-slate-500">From<input id="cb-date-from" type="date" class="mt-1 block h-9 rounded-lg border border-slate-200 px-2 text-xs font-normal"></label>
                    <label class="text-[10px] font-semibold uppercase text-slate-500">To<input id="cb-date-to" type="date" class="mt-1 block h-9 rounded-lg border border-slate-200 px-2 text-xs font-normal"></label>
                    <a id="cb-export" href="{{ route('cash-bank.export.csv') }}" class="apm-outline-button text-center">Export CSV</a>
                </header>
                <div class="overflow-x-auto"><table class="w-full min-w-[1180px] text-xs"><thead class="bg-slate-50 text-[10px] uppercase text-slate-500"><tr><th class="px-4 py-3 text-left">Date</th><th class="px-4 py-3 text-left">Reference</th><th class="px-4 py-3 text-left">Type / Source</th><th class="px-4 py-3 text-left">Account</th><th class="px-4 py-3 text-left">Counterpart</th><th class="px-4 py-3 text-left">Description</th><th class="px-4 py-3 text-right">Amount</th><th class="px-4 py-3 text-center">Status</th><th class="px-4 py-3 text-right">Actions</th></tr></thead><tbody id="cb-transaction-rows"></tbody></table></div>
                <footer class="flex items-center justify-between border-t border-slate-100 px-4 py-3"><p id="cb-transaction-count" class="text-xs text-slate-500"></p><div id="cb-pagination" class="flex gap-1"></div></footer>
            </div>
        </section>

        <section class="mt-4 hidden" data-cb-panel="reconciliation">
            <div class="grid gap-4 xl:grid-cols-[1.45fr_1fr]">
                <form id="cb-reconciliation-form" class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm" novalidate>
                    <div><h2 class="font-semibold text-slate-900">Bank reconciliation</h2><p class="mt-1 text-xs text-slate-500">Match posted book movements to a manually entered statement balance.</p></div>
                    <div class="mt-4 grid gap-3 sm:grid-cols-3"><label class="text-xs text-slate-600">Account *<select name="account_code" class="mt-1 h-9 w-full rounded-lg border border-slate-200 px-2" required><option value="">Select an active account</option>@foreach($activeCashAccounts as $account)<option value="{{ $account['code'] }}">{{ $account['code'] }} · {{ $account['name'] }}</option>@endforeach</select></label><label class="text-xs text-slate-600">Statement date *<input name="statement_date" type="date" value="{{ now()->toDateString() }}" class="mt-1 h-9 w-full rounded-lg border border-slate-200 px-2" required></label><label class="text-xs text-slate-600">Statement balance *<input name="statement_balance" type="number" step="0.01" class="mt-1 h-9 w-full rounded-lg border border-slate-200 px-2" required></label></div>
                    <div id="cb-reconciliation-summary" class="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4"></div>
                    <div class="mt-4 max-h-80 overflow-auto rounded-lg border border-slate-200"><table class="w-full min-w-[650px] text-xs"><thead class="sticky top-0 bg-slate-50"><tr><th class="p-2 text-left">Clear</th><th class="p-2 text-left">Date</th><th class="p-2 text-left">Reference</th><th class="p-2 text-left">Source</th><th class="p-2 text-left">Description</th><th class="p-2 text-right">Amount</th></tr></thead><tbody id="cb-reconcile-rows"><tr><td colspan="6" class="p-8 text-center text-slate-500">Select an account to begin.</td></tr></tbody></table></div>
                    <label class="mt-3 block text-xs text-slate-600">Notes<textarea name="notes" maxlength="255" rows="2" class="mt-1 w-full rounded-lg border border-slate-200 p-2"></textarea></label>
                    <p data-reconciliation-message class="mt-3 hidden rounded-lg p-3 text-xs" role="status"></p><div class="mt-4 flex justify-end"><button id="cb-reconcile-submit" class="apm-primary-button" type="submit" @disabled(! $canManage)>Complete Reconciliation</button></div>
                </form>
                <div class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-semibold text-slate-900">Reconciliation history</h2><div id="cb-reconciliation-history" class="mt-4 space-y-3"></div></div>
            </div>
        </section>
    </div>
</main>

<div id="cb-transaction-modal" class="fixed inset-0 z-50 hidden items-center justify-center p-4" role="dialog" aria-modal="true" aria-hidden="true" aria-labelledby="cb-transaction-title"><button class="absolute inset-0 bg-slate-950/55" data-cb-close="transaction" aria-label="Close"></button><form id="cb-transaction-form" class="relative z-10 max-h-[calc(100dvh-2rem)] w-full max-w-2xl overflow-y-auto rounded-xl bg-white p-5 shadow-2xl" novalidate>
    <div class="flex items-start justify-between"><div><h2 id="cb-transaction-title" class="font-semibold text-slate-900">Record transaction</h2><p class="mt-1 text-xs text-slate-500">Only actual active accounts from Chart of Accounts are available.</p></div><button type="button" class="apm-icon-button" data-cb-close="transaction"><i class="fa-solid fa-xmark"></i></button></div>
    <input name="request_token" type="hidden"><input name="type" type="hidden">
    <div class="mt-4 grid gap-3 sm:grid-cols-2">
        <label class="text-xs text-slate-600">Date *<input name="date" type="date" class="mt-1 h-9 w-full rounded-lg border border-slate-200 px-2" required></label><label class="text-xs text-slate-600">Amount *<input name="amount" type="number" min="0.01" step="0.01" class="mt-1 h-9 w-full rounded-lg border border-slate-200 px-2" required></label>
        <label data-standard-account class="text-xs text-slate-600">Cash / bank account *<select name="account_code" class="mt-1 h-9 w-full rounded-lg border border-slate-200 px-2"></select></label>
        <label data-purpose-field class="text-xs text-slate-600">Purpose *<select name="purpose" class="mt-1 h-9 w-full rounded-lg border border-slate-200 px-2"></select></label>
        <label data-offset-field class="text-xs text-slate-600 sm:col-span-2">Offset account *<input name="offset_search" type="search" class="mt-1 h-9 w-full rounded-t-lg border border-slate-200 px-2" placeholder="Search eligible actual accounts"><select name="offset_account_code" size="5" class="w-full rounded-b-lg border border-t-0 border-slate-200 px-2 py-1"></select><span id="cb-offset-empty" class="mt-1 hidden text-[11px] text-amber-700"></span></label>
        <label data-transfer-account class="hidden text-xs text-slate-600">From account *<select name="from_account_code" class="mt-1 h-9 w-full rounded-lg border border-slate-200 px-2"></select></label><label data-transfer-account class="hidden text-xs text-slate-600">To account *<select name="to_account_code" class="mt-1 h-9 w-full rounded-lg border border-slate-200 px-2"></select></label>
        <label class="text-xs text-slate-600 sm:col-span-2">Reference<input name="reference" maxlength="50" class="mt-1 h-9 w-full rounded-lg border border-slate-200 px-2"></label><label class="text-xs text-slate-600 sm:col-span-2">Description *<textarea name="description" maxlength="180" rows="2" class="mt-1 w-full rounded-lg border border-slate-200 p-2" required></textarea></label>
    </div>
    <div id="cb-transaction-preview" class="mt-4 rounded-lg border border-slate-200 bg-slate-50 p-3 text-xs"></div><p data-transaction-message class="mt-3 hidden rounded-lg p-3 text-xs" role="status"></p><div class="mt-4 flex justify-end gap-2"><button type="button" class="apm-outline-button" data-cb-close="transaction">Cancel</button><button id="cb-transaction-submit" type="submit" class="apm-primary-button">Post Transaction</button></div>
</form></div>

<div id="cb-account-modal" class="fixed inset-0 z-50 hidden items-center justify-center p-4" role="dialog" aria-modal="true" aria-hidden="true"><button class="absolute inset-0 bg-slate-950/55" data-cb-close="account" aria-label="Close"></button><form id="cb-account-form" class="relative z-10 w-full max-w-md rounded-xl bg-white p-5 shadow-2xl" novalidate><div class="flex justify-between"><div><h2 id="cb-account-title" class="font-semibold text-slate-900">Add cash or bank account</h2><p id="cb-account-code" class="mt-1 text-xs text-slate-500"></p></div><button type="button" class="apm-icon-button" data-cb-close="account"><i class="fa-solid fa-xmark"></i></button></div><input name="code" type="hidden"><label class="mt-4 block text-xs text-slate-600">Account name *<input name="name" maxlength="100" class="mt-1 h-9 w-full rounded-lg border border-slate-200 px-2" required></label><label class="mt-3 block text-xs text-slate-600">Account type *<select name="kind" class="mt-1 h-9 w-full rounded-lg border border-slate-200 px-2"><option value="Bank">Bank</option><option value="Cash">Cash</option></select></label><p class="mt-3 rounded-lg bg-blue-50 p-3 text-[11px] text-blue-700">New accounts start at zero. Existing balances are never changed here.</p><p data-account-message class="mt-3 hidden rounded-lg p-3 text-xs"></p><div class="mt-4 flex justify-end gap-2"><button type="button" class="apm-outline-button" data-cb-close="account">Cancel</button><button type="submit" class="apm-primary-button">Save Account</button></div></form></div>

<div id="cb-adjust-modal" class="fixed inset-0 z-50 hidden items-center justify-center p-4" role="dialog" aria-modal="true" aria-hidden="true"><button class="absolute inset-0 bg-slate-950/55" data-cb-close="adjust" aria-label="Close"></button><form id="cb-adjust-form" class="relative z-10 max-h-[calc(100dvh-2rem)] w-full max-w-2xl overflow-y-auto rounded-xl bg-white p-5 shadow-2xl" novalidate><div class="flex justify-between"><div><h2 class="font-semibold text-slate-900">Adjust posted balance</h2><p id="cb-adjust-account" class="mt-1 text-xs text-slate-500"></p></div><button type="button" class="apm-icon-button" data-cb-close="adjust"><i class="fa-solid fa-xmark"></i></button></div><input name="request_token" type="hidden"><input name="account_code" type="hidden"><div class="mt-4 grid gap-3 sm:grid-cols-2"><label class="text-xs text-slate-600">Direction *<select name="direction" class="mt-1 h-9 w-full rounded-lg border border-slate-200 px-2"><option value="increase">Increase</option><option value="decrease">Decrease</option></select></label><label class="text-xs text-slate-600">Amount *<input name="amount" type="number" min="0.01" step="0.01" class="mt-1 h-9 w-full rounded-lg border border-slate-200 px-2" required></label><label class="text-xs text-slate-600">Date *<input name="date" type="date" class="mt-1 h-9 w-full rounded-lg border border-slate-200 px-2" required></label><label class="text-xs text-slate-600">Purpose *<select name="purpose" class="mt-1 h-9 w-full rounded-lg border border-slate-200 px-2"></select></label><label class="text-xs text-slate-600 sm:col-span-2">Offset account *<input name="offset_search" type="search" class="mt-1 h-9 w-full rounded-t-lg border border-slate-200 px-2" placeholder="Search eligible actual accounts"><select name="offset_account_code" size="5" class="w-full rounded-b-lg border border-t-0 border-slate-200 px-2 py-1"></select><span id="cb-adjust-offset-empty" class="mt-1 hidden text-[11px] text-amber-700"></span></label><label class="text-xs text-slate-600">Reference *<input name="reference" maxlength="50" class="mt-1 h-9 w-full rounded-lg border border-slate-200 px-2" required></label><label class="text-xs text-slate-600 sm:col-span-2">Reason *<textarea name="reason" maxlength="180" rows="2" class="mt-1 w-full rounded-lg border border-slate-200 p-2" required></textarea></label></div><div id="cb-adjust-preview" class="mt-4 rounded-lg border border-slate-200 bg-slate-50 p-3 text-xs"></div><p data-adjust-message class="mt-3 hidden rounded-lg p-3 text-xs"></p><div class="mt-4 flex justify-end gap-2"><button type="button" class="apm-outline-button" data-cb-close="adjust">Cancel</button><button type="submit" class="apm-primary-button">Post Adjustment</button></div></form></div>

<div id="cb-activity-modal" class="fixed inset-0 z-50 hidden items-center justify-center p-4" role="dialog" aria-modal="true" aria-hidden="true"><button class="absolute inset-0 bg-slate-950/55" data-cb-close="activity" aria-label="Close"></button><section class="relative z-10 max-h-[calc(100dvh-2rem)] w-full max-w-5xl overflow-y-auto rounded-xl bg-white p-5 shadow-2xl"><div class="flex justify-between"><div><h2 id="cb-activity-title" class="font-semibold text-slate-900">Account activity</h2><p id="cb-activity-summary" class="mt-1 text-xs text-slate-500"></p></div><button type="button" class="apm-icon-button" data-cb-close="activity"><i class="fa-solid fa-xmark"></i></button></div><div class="mt-4 grid gap-2 sm:grid-cols-3"><input id="cb-activity-search" type="search" class="h-9 rounded-lg border border-slate-200 px-3 text-xs" placeholder="Search activity"><input id="cb-activity-from" type="date" class="h-9 rounded-lg border border-slate-200 px-2 text-xs"><input id="cb-activity-to" type="date" class="h-9 rounded-lg border border-slate-200 px-2 text-xs"></div><div class="mt-4 overflow-x-auto rounded-lg border border-slate-200"><table class="w-full min-w-[900px] text-xs"><thead class="bg-slate-50 text-[10px] uppercase text-slate-500"><tr><th class="p-3 text-left">Date</th><th class="p-3 text-left">Reference</th><th class="p-3 text-left">Source</th><th class="p-3 text-left">Counterpart</th><th class="p-3 text-right">Debit</th><th class="p-3 text-right">Credit</th><th class="p-3 text-right">Running balance</th></tr></thead><tbody id="cb-activity-rows"><tr><td colspan="7" class="p-10 text-center text-slate-500">Loading activity…</td></tr></tbody></table></div></section></div>

<div id="cb-detail-modal" class="fixed inset-0 z-50 hidden items-center justify-center p-4" role="dialog" aria-modal="true" aria-hidden="true"><button class="absolute inset-0 bg-slate-950/55" data-cb-close="detail" aria-label="Close"></button><section class="relative z-10 w-full max-w-lg rounded-xl bg-white p-5 shadow-2xl"><div class="flex justify-between"><h2 class="font-semibold text-slate-900">Transaction details</h2><button type="button" class="apm-icon-button" data-cb-close="detail"><i class="fa-solid fa-xmark"></i></button></div><div id="cb-detail-content" class="mt-4"></div></section></div>

<script id="cb-data" type="application/json">{!! json_encode(['cashAccounts' => $cashAccounts, 'activeCashAccounts' => $activeCashAccounts, 'postingAccounts' => $postingAccounts, 'transactions' => $transactions, 'reconciliations' => $reconciliations], JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_UNESCAPED_SLASHES) !!}</script>
@endsection
