@extends('layouts.accounting', ['pageTitle' => 'Expenses', 'activePage' => 'expenses'])

@section('content')
<main id="expenses-page" class="p-4 sm:p-5" data-store-url="{{ route('expenses.store') }}" data-payment-url="{{ route('expense-payments.store') }}" data-csv-url="{{ route('expenses.export.csv') }}" data-user-role="{{ $user['role'] }}">
    <div class="dashboard-enter">
        <nav aria-label="Breadcrumb" class="flex items-center gap-2 text-xs text-slate-500"><span>Accounting</span><span class="text-slate-300">/</span><span class="font-medium text-slate-700">Expenses</span></nav>
        <div class="mt-4 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
            <div><h1 class="text-xl font-bold text-slate-900">Expenses</h1><p class="mt-1 text-xs text-slate-500">Record, review, and post business expenses with supporting receipts.</p></div>
            @if ($demoCan('drafts.manage'))<button id="expense-new" type="button" class="apm-primary-button print:hidden"><i class="fa-solid fa-plus" aria-hidden="true"></i> New Expense</button>@endif
        </div>

        <section class="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4" aria-label="Expense summary">
            <article class="apm-summary-card"><p>Posted Expenses</p><strong>&#8369;{{ number_format($metrics['total'], 2) }}</strong><span>Approved gross amount in ledger</span></article>
            <article class="apm-summary-card"><p>Approved Documents</p><strong>{{ collect($expenses)->where('status', 'Approved')->count() }}</strong><span>&#8369;{{ number_format($metrics['approved'], 2) }} gross value</span></article>
            <article class="apm-summary-card"><p>Pending Review</p><strong>&#8369;{{ number_format($metrics['pending'], 2) }}</strong><span>Awaiting approval</span></article>
            <article class="apm-summary-card"><p>Drafts</p><strong>{{ $metrics['draft_count'] }}</strong><span>{{ $metrics['receipts'] }} records with receipts</span></article>
        </section>

        <section class="mt-5 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm print:hidden">
            <header class="border-b border-slate-200 px-4 py-3"><h2 class="text-sm font-semibold text-slate-900">Expense Payments</h2><p class="mt-0.5 text-[10px] text-slate-500">Full settlement of approved unpaid expenses</p></header>
            <div class="overflow-x-auto"><table class="w-full min-w-[850px] text-xs"><thead class="bg-slate-50 text-[10px] uppercase text-slate-500"><tr><th class="px-4 py-3 text-left">Payment</th><th class="px-4 py-3 text-left">Expense</th><th class="px-4 py-3 text-left">Date</th><th class="px-4 py-3 text-left">Payee</th><th class="px-4 py-3 text-right">Amount</th><th class="px-4 py-3 text-left">Journal</th><th class="px-4 py-3 text-left">Status</th><th class="px-4 py-3 text-right">Actions</th></tr></thead><tbody id="expense-payment-rows"></tbody></table></div>
        </section>

        <section class="mt-5 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">
            <header class="flex flex-col gap-3 border-b border-slate-200 p-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="text-sm font-semibold text-slate-900">Expense Records</h2><p id="expense-result-count" class="mt-0.5 text-[10px] text-slate-500"></p></div><div class="flex gap-2 print:hidden"><a href="{{ route('expenses.export.csv') }}" class="apm-outline-button"><i class="fa-solid fa-file-csv"></i> Export</a><button type="button" data-print-page class="apm-outline-button"><i class="fa-solid fa-print"></i> Print</button></div></header>
            <div class="grid gap-2 border-b border-slate-200 p-4 sm:grid-cols-2 xl:grid-cols-6 print:hidden">
                <input id="expense-search" type="search" placeholder="Search payee, memo, or number" aria-label="Search expenses" class="h-9 rounded-lg border border-slate-200 px-3 text-xs xl:col-span-2">
                <select id="expense-category-filter" aria-label="Category filter" class="h-9 rounded-lg border border-slate-200 px-3 text-xs"><option value="">All Categories</option>@foreach($expenseAccounts as $account)<option value="{{ $account['code'] }}">{{ $account['name'] }}</option>@endforeach</select>
                <select id="expense-status-filter" aria-label="Status filter" class="h-9 rounded-lg border border-slate-200 px-3 text-xs"><option value="">All Statuses</option><option>Draft</option><option>For Review</option><option>Approved</option><option>Reversed</option></select>
                <input id="expense-date-from" type="date" aria-label="Date from" class="h-9 rounded-lg border border-slate-200 px-3 text-xs">
                <input id="expense-date-to" type="date" aria-label="Date to" class="h-9 rounded-lg border border-slate-200 px-3 text-xs">
                <input id="expense-min" type="number" min="0" step="0.01" placeholder="Min amount" aria-label="Minimum amount" class="h-9 rounded-lg border border-slate-200 px-3 text-xs">
                <input id="expense-max" type="number" min="0" step="0.01" placeholder="Max amount" aria-label="Maximum amount" class="h-9 rounded-lg border border-slate-200 px-3 text-xs">
                <select id="expense-payment-filter" aria-label="Payment status filter" class="h-9 rounded-lg border border-slate-200 px-3 text-xs"><option value="">Paid &amp; Unpaid</option><option>Paid</option><option>Unpaid</option></select>
                <button id="expense-clear-filters" type="button" class="apm-outline-button">Clear filters</button>
            </div>
            <div class="overflow-x-auto"><table class="w-full min-w-[1050px] text-xs"><thead class="bg-slate-50 text-[10px] uppercase text-slate-500"><tr><th class="px-4 py-3 text-left"><button type="button" data-expense-sort="expense_number">Expense ID <i class="fa-solid fa-sort"></i></button></th><th class="px-4 py-3 text-left"><button type="button" data-expense-sort="date">Date <i class="fa-solid fa-sort"></i></button></th><th class="px-4 py-3 text-left">Payee / Memo</th><th class="px-4 py-3 text-left">Category</th><th class="px-4 py-3 text-left">Payment</th><th class="px-4 py-3 text-right"><button type="button" data-expense-sort="total">Amount <i class="fa-solid fa-sort"></i></button></th><th class="px-4 py-3 text-center">Receipt</th><th class="px-4 py-3 text-left">Submitted By</th><th class="px-4 py-3 text-center">Status</th><th class="px-4 py-3 text-right print:hidden">Actions</th></tr></thead><tbody id="expense-rows"></tbody></table></div>
            <footer class="flex items-center justify-between border-t border-slate-200 px-4 py-3 text-[10px] text-slate-500 print:hidden"><span id="expense-page-summary"></span><div class="flex items-center gap-2"><button id="expense-prev" class="apm-outline-button" type="button">Previous</button><span id="expense-page-number" class="grid size-7 place-items-center rounded-md bg-blue-600 font-semibold text-white">1</span><button id="expense-next" class="apm-outline-button" type="button">Next</button></div></footer>
        </section>
    </div>
</main>

<div id="expense-form-modal" class="fixed inset-0 z-50 hidden items-center justify-center p-4" role="dialog" aria-modal="true" aria-hidden="true" aria-labelledby="expense-form-title"><button class="absolute inset-0 bg-slate-950/55" data-expense-close="form" aria-label="Close expense form"></button><form id="expense-form" class="relative z-10 max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-xl bg-white p-5 shadow-2xl" novalidate><div class="flex items-start justify-between"><div><h2 id="expense-form-title" class="font-semibold text-slate-900">New Expense</h2><p class="mt-1 text-xs text-slate-500">Save a draft or submit it for approval.</p></div><button type="button" class="apm-icon-button" data-expense-close="form"><i class="fa-solid fa-xmark"></i></button></div><input name="request_token" type="hidden"><input name="expense_number" type="hidden">
    <div class="mt-4 grid gap-3 sm:grid-cols-2">
        <label class="text-xs text-slate-600">Expense date *<input name="date" type="date" required class="mt-1 h-9 w-full rounded-lg border border-slate-200 px-3"><span data-error="date" class="mt-1 block text-[10px] text-rose-600"></span></label>
        <label class="text-xs text-slate-600">Payee *<input name="payee" maxlength="100" required class="mt-1 h-9 w-full rounded-lg border border-slate-200 px-3"><span data-error="payee" class="mt-1 block text-[10px] text-rose-600"></span></label>
        <label class="text-xs text-slate-600">Category / expense account *<select name="category_account_code" required class="mt-1 h-9 w-full rounded-lg border border-slate-200 px-3"><option value="">Select category</option>@foreach($expenseAccounts as $account)<option value="{{ $account['code'] }}">{{ $account['code'] }} · {{ $account['name'] }}</option>@endforeach</select><span data-error="category_account_code" class="mt-1 block text-[10px] text-rose-600"></span></label>
        <label class="text-xs text-slate-600">Amount before tax *<input name="amount" type="number" min="0.01" step="0.01" required class="mt-1 h-9 w-full rounded-lg border border-slate-200 px-3"><span data-error="amount" class="mt-1 block text-[10px] text-rose-600"></span></label>
        <label class="text-xs text-slate-600">Tax configuration *<select name="tax_rate" class="mt-1 h-9 w-full rounded-lg border border-slate-200 px-3">@forelse($vatRates as $taxCode)<option value="{{ $taxCode['rate'] }}" @selected($taxCode['is_default'])>{{ $taxCode['code'] }} · {{ $taxCode['name'] }} ({{ number_format($taxCode['rate'], 2) }}%)</option>@empty<option value="0">No active VAT codes</option>@endforelse</select></label>
        <label class="text-xs text-slate-600">Payment status *<select name="payment_status" class="mt-1 h-9 w-full rounded-lg border border-slate-200 px-3"><option>Paid</option><option>Unpaid</option></select></label>
        <label data-payment-method class="text-xs text-slate-600">Payment method *<select name="payment_method" class="mt-1 h-9 w-full rounded-lg border border-slate-200 px-3"><option>Cash</option><option>Credit Card</option><option>Bank Transfer</option><option>Other</option></select></label>
        <label data-expense-due-date class="hidden text-xs text-slate-600">Due date *<input name="due_date" type="date" class="mt-1 h-9 w-full rounded-lg border border-slate-200 px-3"><span data-error="due_date" class="mt-1 block text-[10px] text-rose-600"></span></label>
        <label data-cash-account class="text-xs text-slate-600">Cash / bank account *<select name="cash_account_code" class="mt-1 h-9 w-full rounded-lg border border-slate-200 px-3"><option value="">Select account</option>@foreach($cashAccounts as $account)<option value="{{ $account['code'] }}">{{ $account['name'] }} — &#8369;{{ number_format($account['balance'], 2) }}</option>@endforeach</select><span data-error="cash_account_code" class="mt-1 block text-[10px] text-rose-600"></span></label>
        <label class="text-xs text-slate-600 sm:col-span-2">Memo *<textarea name="memo" maxlength="180" rows="2" required class="mt-1 w-full rounded-lg border border-slate-200 p-3"></textarea><span data-error="memo" class="mt-1 block text-[10px] text-rose-600"></span></label>
        <label class="text-xs text-slate-600 sm:col-span-2">Supporting receipt <span class="text-slate-400">(JPG, PNG, or PDF · max 5 MB · demo preview only)</span><input id="expense-receipt" type="file" accept="image/jpeg,image/png,application/pdf" class="mt-1 block w-full rounded-lg border border-dashed border-slate-300 p-3 text-xs"><span data-error="receipt" class="mt-1 block text-[10px] text-rose-600"></span><span id="expense-receipt-preview" class="mt-2 hidden rounded-lg bg-slate-50 p-3 text-xs text-slate-600"></span></label>
    </div>
    <div class="mt-3 rounded-lg bg-blue-50 p-3 text-xs"><div class="flex justify-between"><span class="text-blue-700">Tax</span><strong id="expense-tax-preview" class="font-mono text-blue-900">₱0.00</strong></div><div class="mt-1 flex justify-between border-t border-blue-100 pt-2"><span class="font-semibold text-blue-800">Total</span><strong id="expense-total-preview" class="font-mono text-blue-900">₱0.00</strong></div></div>
    <p data-expense-message class="mt-3 hidden rounded-lg p-3 text-xs"></p><div class="mt-4 flex flex-wrap justify-end gap-2"><button type="button" class="apm-outline-button" data-expense-close="form">Cancel</button><button type="submit" name="action" value="draft" class="apm-outline-button">Save Draft</button><button type="submit" name="action" value="review" class="apm-primary-button">Submit for Review</button></div>
</form></div>

<div id="expense-view-modal" class="fixed inset-0 z-50 hidden items-center justify-center p-4" role="dialog" aria-modal="true" aria-hidden="true" aria-labelledby="expense-view-title"><button class="absolute inset-0 bg-slate-950/55" data-expense-close="view" aria-label="Close details"></button><article class="relative z-10 w-full max-w-lg rounded-xl bg-white p-5 shadow-2xl"><div class="flex justify-between"><h2 id="expense-view-title" class="font-semibold text-slate-900">Expense Details</h2><button type="button" class="apm-icon-button" data-expense-close="view"><i class="fa-solid fa-xmark"></i></button></div><div id="expense-view-content" class="mt-4"></div><div class="mt-4 flex justify-end"><button type="button" class="apm-outline-button" data-expense-close="view">Close</button></div></article></div>

<div id="expense-payment-modal" class="fixed inset-0 z-50 hidden items-center justify-center p-4" role="dialog" aria-modal="true" aria-hidden="true" aria-labelledby="expense-payment-title"><button class="absolute inset-0 bg-slate-950/55" data-expense-close="payment" aria-label="Close payment form"></button><form id="expense-payment-form" class="relative z-10 w-full max-w-lg rounded-xl bg-white p-5 shadow-2xl" novalidate><div class="flex justify-between"><div><h2 id="expense-payment-title" class="font-semibold text-slate-900">Expense Payment</h2><p class="mt-1 text-xs text-slate-500">Full settlement; posting requires Accountant or Administrator.</p></div><button type="button" class="apm-icon-button" data-expense-close="payment"><i class="fa-solid fa-xmark"></i></button></div><input name="request_token" type="hidden"><input name="payment_number" type="hidden"><input name="expense_number" type="hidden"><div class="mt-4 grid gap-3 sm:grid-cols-2"><label class="text-xs text-slate-600">Expense<input name="expense_display" disabled class="mt-1 h-9 w-full rounded-lg border border-slate-200 bg-slate-50 px-3"></label><label class="text-xs text-slate-600">Full amount<input name="amount_display" disabled class="mt-1 h-9 w-full rounded-lg border border-slate-200 bg-slate-50 px-3"></label><label class="text-xs text-slate-600">Payment date *<input name="payment_date" type="date" required class="mt-1 h-9 w-full rounded-lg border border-slate-200 px-3"><span data-payment-error="payment_date" class="text-[10px] text-rose-600"></span></label><label class="text-xs text-slate-600">Cash / bank *<select name="cash_account_code" required class="mt-1 h-9 w-full rounded-lg border border-slate-200 px-3"><option value="">Select account</option>@foreach($cashAccounts as $account)<option value="{{ $account['code'] }}">{{ $account['name'] }} — &#8369;{{ number_format($account['balance'], 2) }}</option>@endforeach</select><span data-payment-error="cash_account_code" class="text-[10px] text-rose-600"></span></label><label class="text-xs text-slate-600">Method *<select name="payment_method" class="mt-1 h-9 w-full rounded-lg border border-slate-200 px-3"><option>Cash</option><option>Credit Card</option><option>Bank Transfer</option><option>Other</option></select></label><label class="text-xs text-slate-600">Reference<input name="reference" maxlength="50" class="mt-1 h-9 w-full rounded-lg border border-slate-200 px-3"></label><label class="text-xs text-slate-600 sm:col-span-2">Memo<input name="memo" maxlength="180" class="mt-1 h-9 w-full rounded-lg border border-slate-200 px-3"></label></div><p data-expense-payment-message class="mt-3 hidden rounded-lg p-3 text-xs"></p><div class="mt-4 flex justify-end gap-2"><button type="button" class="apm-outline-button" data-expense-close="payment">Cancel</button><button type="submit" class="apm-primary-button">Save Draft</button></div></form></div>

<script id="expense-data" type="application/json">{!! json_encode(['expenses' => $expenses, 'payments' => $expensePayments], JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_UNESCAPED_SLASHES) !!}</script>
@endsection
