@extends('layouts.accounting', ['pageTitle' => 'Tax Settings', 'activePage' => 'tax-settings'])

@section('content')
<main id="tax-settings-page" class="p-4 sm:p-5" data-store-url="{{ route('tax-settings.store') }}" data-summary-url="{{ route('tax-settings.summary') }}" data-export-url="{{ route('tax-settings.export.csv') }}" data-user-role="{{ $user['role'] }}">
    <div class="dashboard-enter">
        <nav aria-label="Breadcrumb" class="flex items-center gap-2 text-xs text-slate-500 print:hidden"><span>Administration</span><span class="text-slate-300">/</span><span class="font-medium text-slate-700">Tax / VAT Settings</span></nav>
        <div class="mt-4 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between print:hidden">
            <div><h1 class="text-xl font-bold text-slate-900">Tax / VAT Settings</h1><p class="mt-1 text-xs text-slate-500">Manage demo tax codes, default VAT rates, and posted tax activity.</p></div>
            @if($user['role'] === 'Administrator')<button id="tax-add" type="button" class="apm-primary-button"><i class="fa-solid fa-plus" aria-hidden="true"></i> Add Tax Rate</button>@endif
        </div>

        <div class="mt-4 flex items-start gap-3 rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs text-amber-800 print:hidden"><i class="fa-solid fa-triangle-exclamation mt-0.5" aria-hidden="true"></i><p><strong>Demonstration configuration only.</strong> These rates simulate accounting workflows and are not tax or regulatory advice. Historical posted transactions retain their original amounts when settings change.</p></div>

        <section id="tax-metrics" class="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4" aria-label="Tax summary">
            <article class="apm-summary-card"><p>Output VAT</p><strong data-tax-metric="output" class="!text-blue-600">&#8369;{{ number_format($summary['metrics']['output'], 2) }}</strong><span>Posted sales tax</span></article>
            <article class="apm-summary-card"><p>Input VAT</p><strong data-tax-metric="input" class="!text-emerald-600">&#8369;{{ number_format($summary['metrics']['input'], 2) }}</strong><span>Posted purchase tax</span></article>
            <article class="apm-summary-card"><p>Net VAT Payable / (Credit)</p><strong data-tax-metric="net" class="{{ $summary['metrics']['net'] < 0 ? '!text-emerald-600' : '!text-rose-600' }}">&#8369;{{ number_format($summary['metrics']['net'], 2) }}</strong><span>Output less input VAT</span></article>
            <article class="apm-summary-card"><p>EWT Withheld</p><strong data-tax-metric="ewt" class="!text-amber-600">&#8369;{{ number_format($summary['metrics']['ewt'], 2) }}</strong><span>Posted withholding entries</span></article>
        </section>

        <div class="mt-5 flex gap-1 border-b border-slate-200 print:hidden" role="tablist">
            <button type="button" class="apm-tab border-blue-600 text-blue-600" data-tax-tab="rates" role="tab" aria-selected="true">Tax Rates</button>
            <button type="button" class="apm-tab" data-tax-tab="summary" role="tab" aria-selected="false">VAT Summary</button>
        </div>

        <section class="mt-4 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm" data-tax-panel="rates">
            <header class="flex flex-col gap-3 border-b border-slate-200 p-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="text-sm font-semibold text-slate-900">Configured Tax Rates</h2><p id="tax-rate-count" class="mt-0.5 text-[10px] text-slate-500"></p></div><a href="{{ route('tax-settings.export.csv', ['view' => 'rates']) }}" class="apm-outline-button print:hidden"><i class="fa-solid fa-file-csv"></i> Export</a></header>
            <div class="grid gap-2 border-b border-slate-200 p-4 sm:grid-cols-3 print:hidden"><input id="tax-search" type="search" placeholder="Search code, name, or use" aria-label="Search tax rates" class="h-9 rounded-lg border border-slate-200 px-3 text-xs"><select id="tax-type-filter" aria-label="Tax type" class="h-9 rounded-lg border border-slate-200 px-3 text-xs"><option value="">All Types</option><option>VAT</option><option>EWT</option><option>DST</option></select><select id="tax-status-filter" aria-label="Tax status" class="h-9 rounded-lg border border-slate-200 px-3 text-xs"><option value="">All Statuses</option><option>Active</option><option>Inactive</option></select></div>
            <div class="overflow-x-auto"><table class="w-full min-w-[850px] text-xs"><thead class="bg-slate-50 text-[10px] uppercase text-slate-500"><tr><th class="px-4 py-3 text-left"><button type="button" data-tax-sort="code">Code <i class="fa-solid fa-sort"></i></button></th><th class="px-4 py-3 text-left"><button type="button" data-tax-sort="name">Tax Name <i class="fa-solid fa-sort"></i></button></th><th class="px-4 py-3 text-right"><button type="button" data-tax-sort="rate">Rate <i class="fa-solid fa-sort"></i></button></th><th class="px-4 py-3 text-center">Type</th><th class="px-4 py-3 text-left">Applies To</th><th class="px-4 py-3 text-center">Status</th><th class="px-4 py-3 text-right print:hidden">Actions</th></tr></thead><tbody id="tax-rate-rows"></tbody></table></div>
            <footer class="flex items-center justify-between border-t border-slate-200 px-4 py-3 text-[10px] text-slate-500 print:hidden"><span id="tax-page-summary"></span><div class="flex items-center gap-2"><button id="tax-prev" type="button" class="apm-outline-button">Previous</button><span id="tax-page-number" class="grid size-7 place-items-center rounded-md bg-blue-600 font-semibold text-white">1</span><button id="tax-next" type="button" class="apm-outline-button">Next</button></div></footer>
        </section>

        <section class="mt-4 hidden overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm" data-tax-panel="summary">
            <header class="flex flex-col gap-3 border-b border-slate-200 p-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="text-sm font-semibold text-slate-900">VAT / Withholding Summary</h2><p class="mt-0.5 text-[10px] text-slate-500">Calculated from posted journal tax accounts using the selected demo configuration.</p></div><div class="flex gap-2 print:hidden"><a id="tax-summary-export" href="#" class="apm-outline-button"><i class="fa-solid fa-file-csv"></i> Export</a><button type="button" data-print-page class="apm-outline-button"><i class="fa-solid fa-print"></i> Print</button></div></header>
            <form id="tax-summary-filters" class="flex flex-wrap items-end gap-2 border-b border-slate-200 p-4 print:hidden"><label class="text-[10px] text-slate-500">From<input name="date_from" type="date" value="{{ $filters['date_from'] }}" class="mt-1 block h-9 rounded-lg border border-slate-200 px-3 text-xs"></label><label class="text-[10px] text-slate-500">To<input name="date_to" type="date" value="{{ $filters['date_to'] }}" class="mt-1 block h-9 rounded-lg border border-slate-200 px-3 text-xs"></label><label class="text-[10px] text-slate-500">Tax code<select name="tax_code" class="mt-1 block h-9 rounded-lg border border-slate-200 px-3 text-xs"><option value="">All configured codes</option>@foreach($taxCodes as $code)<option value="{{ $code['code'] }}">{{ $code['code'] }} · {{ $code['name'] }}</option>@endforeach</select></label><button type="submit" class="apm-primary-button"><i class="fa-solid fa-rotate"></i> Generate</button><p id="tax-summary-error" class="hidden w-full rounded-lg bg-rose-50 p-2 text-xs text-rose-700"></p></form>
            <div id="tax-summary-loading" class="hidden p-12 text-center"><i class="fa-solid fa-spinner fa-spin text-2xl text-blue-600"></i><p class="mt-2 text-xs text-slate-500">Calculating posted tax activity…</p></div>
            <div id="tax-summary-content" class="overflow-x-auto"><table class="w-full min-w-[850px] text-xs"><thead class="bg-slate-50 text-[10px] uppercase text-slate-500"><tr><th class="px-4 py-3 text-left">Date</th><th class="px-4 py-3 text-left">Reference</th><th class="px-4 py-3 text-left">Tax Code</th><th class="px-4 py-3 text-left">Direction</th><th class="px-4 py-3 text-right">Rate</th><th class="px-4 py-3 text-right">Taxable Amount</th><th class="px-4 py-3 text-right">Tax Amount</th></tr></thead><tbody id="tax-summary-rows"></tbody><tfoot id="tax-summary-foot" class="border-t-2 border-slate-700 bg-slate-50 font-bold"></tfoot></table></div>
            <footer class="flex justify-between border-t border-slate-100 px-4 py-3 text-[10px] text-slate-400"><span id="tax-summary-count"></span><span id="tax-summary-generated"></span></footer>
        </section>
    </div>
</main>

<div id="tax-form-modal" class="fixed inset-0 z-50 hidden items-center justify-center p-4" role="dialog" aria-modal="true" aria-hidden="true" aria-labelledby="tax-form-title"><button type="button" class="absolute inset-0 bg-slate-950/55" data-tax-close aria-label="Close tax form"></button><form id="tax-form" class="relative z-10 w-full max-w-lg rounded-xl bg-white p-5 shadow-2xl" novalidate><div class="flex items-start justify-between"><div><h2 id="tax-form-title" class="font-semibold text-slate-900">Add Tax Rate</h2><p class="mt-1 text-xs text-slate-500">Configure a demonstration tax code and rate.</p></div><button type="button" class="apm-icon-button" data-tax-close><i class="fa-solid fa-xmark"></i></button></div><input name="id" type="hidden"><div class="mt-4 grid gap-3 sm:grid-cols-2"><label class="text-xs text-slate-600">Tax code *<input name="code" maxlength="20" required class="mt-1 h-9 w-full rounded-lg border border-slate-200 px-3 uppercase"><span data-tax-error="code" class="mt-1 block text-[10px] text-rose-600"></span></label><label class="text-xs text-slate-600">Tax name *<input name="name" maxlength="100" required class="mt-1 h-9 w-full rounded-lg border border-slate-200 px-3"><span data-tax-error="name" class="mt-1 block text-[10px] text-rose-600"></span></label><label class="text-xs text-slate-600">Rate (%) *<input name="rate" type="number" min="0" max="100" step="0.01" required class="mt-1 h-9 w-full rounded-lg border border-slate-200 px-3"><span data-tax-error="rate" class="mt-1 block text-[10px] text-rose-600"></span></label><label class="text-xs text-slate-600">Type *<select name="type" class="mt-1 h-9 w-full rounded-lg border border-slate-200 px-3"><option>VAT</option><option>EWT</option><option>DST</option></select></label><label class="text-xs text-slate-600 sm:col-span-2">Applies to *<input name="applies_to" maxlength="100" required placeholder="e.g. Goods & Services" class="mt-1 h-9 w-full rounded-lg border border-slate-200 px-3"><span data-tax-error="applies_to" class="mt-1 block text-[10px] text-rose-600"></span></label><label class="flex items-center gap-2 text-xs text-slate-600 sm:col-span-2"><input name="is_default" type="checkbox" value="1" class="size-4 rounded border-slate-300">Use as the default code for this tax type</label></div><p data-tax-message class="mt-3 hidden rounded-lg p-3 text-xs"></p><div class="mt-4 flex justify-end gap-2"><button type="button" class="apm-outline-button" data-tax-close>Cancel</button><button type="submit" class="apm-primary-button">Save Tax Rate</button></div></form></div>

<div id="tax-view-modal" class="fixed inset-0 z-50 hidden items-center justify-center p-4" role="dialog" aria-modal="true" aria-hidden="true" aria-labelledby="tax-view-title"><button type="button" class="absolute inset-0 bg-slate-950/55" data-tax-view-close aria-label="Close tax details"></button><article class="relative z-10 w-full max-w-md rounded-xl bg-white p-5 shadow-2xl"><div class="flex items-start justify-between"><div><h2 id="tax-view-title" class="font-semibold text-slate-900">Tax Rate Details</h2><p class="mt-1 text-xs text-slate-500">Demonstration tax configuration.</p></div><button type="button" class="apm-icon-button" data-tax-view-close><i class="fa-solid fa-xmark"></i></button></div><div id="tax-view-content" class="mt-4"></div><div class="mt-4 flex justify-end"><button type="button" class="apm-outline-button" data-tax-view-close>Close</button></div></article></div>

<script id="tax-settings-data" type="application/json">{!! json_encode(['taxCodes' => $taxCodes, 'summary' => $summary], JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_UNESCAPED_SLASHES) !!}</script>
@endsection
