<?php

use App\Http\Controllers\AccountsPayableController;
use App\Http\Controllers\AccountsReceivableController;
use App\Http\Controllers\ChartOfAccountsController;
use App\Http\Controllers\ChartOfAccountsExportController;
use App\Http\Controllers\DemoAuthController;
use App\Http\Controllers\GeneralLedgerController;
use App\Http\Controllers\JournalEntryController;
use App\Http\Controllers\SalesRevenueController;
use Illuminate\Support\Facades\Route;

Route::redirect('/', '/login');

Route::get('/login', [DemoAuthController::class, 'show'])->name('login');
Route::post('/login', [DemoAuthController::class, 'login'])->name('login.attempt');
Route::get('/dashboard', [DemoAuthController::class, 'dashboard'])->name('dashboard');
Route::get('/chart-of-accounts', [DemoAuthController::class, 'chartOfAccounts'])->name('chart-of-accounts');
Route::post('/chart-of-accounts', [ChartOfAccountsController::class, 'store'])->name('chart-of-accounts.store');
Route::put('/chart-of-accounts/{code}', [ChartOfAccountsController::class, 'update'])->name('chart-of-accounts.update');
Route::patch('/chart-of-accounts/{code}/status', [ChartOfAccountsController::class, 'status'])->name('chart-of-accounts.status');
Route::delete('/chart-of-accounts/{code}', [ChartOfAccountsController::class, 'destroy'])->name('chart-of-accounts.destroy');
Route::get('/journal-entries', [JournalEntryController::class, 'index'])->name('journal-entries');
Route::get('/journal-entries/export/csv', [JournalEntryController::class, 'csv'])->name('journal-entries.export.csv');
Route::get('/journal-entries/export/pdf', [JournalEntryController::class, 'pdf'])->name('journal-entries.export.pdf');
Route::get('/journal-entries/{journalNumber}/print', [JournalEntryController::class, 'print'])->name('journal-entries.print');
Route::get('/journal-entries/{journalNumber}/pdf', [JournalEntryController::class, 'entryPdf'])->name('journal-entries.pdf');
Route::post('/journal-entries', [JournalEntryController::class, 'store'])->name('journal-entries.store');
Route::put('/journal-entries/{journalNumber}', [JournalEntryController::class, 'update'])->name('journal-entries.update');
Route::delete('/journal-entries/{journalNumber}', [JournalEntryController::class, 'destroy'])->name('journal-entries.destroy');
Route::post('/journal-entries/{journalNumber}/submit-review', [JournalEntryController::class, 'submitForReview'])->name('journal-entries.submit-review');
Route::post('/journal-entries/{journalNumber}/return-draft', [JournalEntryController::class, 'returnToDraft'])->name('journal-entries.return-draft');
Route::post('/journal-entries/{journalNumber}/post', [JournalEntryController::class, 'post'])->name('journal-entries.post');
Route::post('/journal-entries/{journalNumber}/reverse', [JournalEntryController::class, 'reverse'])->name('journal-entries.reverse');
Route::get('/general-ledger', [GeneralLedgerController::class, 'index'])->name('general-ledger');
Route::get('/general-ledger/data', [GeneralLedgerController::class, 'data'])->name('general-ledger.data');
Route::get('/general-ledger/export/csv', [GeneralLedgerController::class, 'csv'])->name('general-ledger.export.csv');
Route::get('/general-ledger/export/pdf', [GeneralLedgerController::class, 'pdf'])->name('general-ledger.export.pdf');
Route::get('/sales-revenue', [SalesRevenueController::class, 'index'])->name('sales-revenue');
Route::post('/sales-revenue/customers', [SalesRevenueController::class, 'storeCustomer'])->name('sales-revenue.customers.store');
Route::post('/sales-revenue/invoices', [SalesRevenueController::class, 'storeInvoice'])->name('sales-revenue.invoices.store');
Route::post('/sales-revenue/invoices/{invoiceNumber}/post', [SalesRevenueController::class, 'postInvoice'])->name('sales-revenue.invoices.post');
Route::get('/sales-revenue/invoices/{invoiceNumber}/print', [SalesRevenueController::class, 'printInvoice'])->name('sales-revenue.invoices.print');
Route::get('/accounts-receivable', [AccountsReceivableController::class, 'index'])->name('accounts-receivable');
Route::post('/accounts-receivable/payments', [AccountsReceivableController::class, 'storePayment'])->name('accounts-receivable.payments.store');
Route::get('/accounts-receivable/export/csv', [AccountsReceivableController::class, 'csv'])->name('accounts-receivable.export.csv');
Route::get('/accounts-payable', [AccountsPayableController::class, 'index'])->name('accounts-payable');
Route::post('/accounts-payable/vendors', [AccountsPayableController::class, 'storeVendor'])->name('accounts-payable.vendors.store');
Route::put('/accounts-payable/vendors/{id}', [AccountsPayableController::class, 'updateVendor'])->name('accounts-payable.vendors.update');
Route::patch('/accounts-payable/vendors/{id}/status', [AccountsPayableController::class, 'vendorStatus'])->name('accounts-payable.vendors.status');
Route::post('/accounts-payable/bills', [AccountsPayableController::class, 'storeBill'])->name('accounts-payable.bills.store');
Route::put('/accounts-payable/bills/{billNumber}', [AccountsPayableController::class, 'updateBill'])->name('accounts-payable.bills.update');
Route::post('/accounts-payable/bills/{billNumber}/post', [AccountsPayableController::class, 'postBill'])->name('accounts-payable.bills.post');
Route::post('/accounts-payable/payments', [AccountsPayableController::class, 'storePayment'])->name('accounts-payable.payments.store');
Route::get('/accounts-payable/export/csv', [AccountsPayableController::class, 'csv'])->name('accounts-payable.export.csv');
Route::get('/accounts-payable/export/pdf', [AccountsPayableController::class, 'pdf'])->name('accounts-payable.export.pdf');
Route::get('/chart-of-accounts/export/pdf', [ChartOfAccountsExportController::class, 'pdf'])->name('chart-of-accounts.export.pdf');
Route::get('/chart-of-accounts/export/csv', [ChartOfAccountsExportController::class, 'csv'])->name('chart-of-accounts.export.csv');
Route::post('/logout', [DemoAuthController::class, 'logout'])->name('logout');
