<?php

use App\Http\Controllers\AccountsPayableController;
use App\Http\Controllers\AccountsReceivableController;
use App\Http\Controllers\AuditTrailController;
use App\Http\Controllers\CashBankController;
use App\Http\Controllers\ChartOfAccountsController;
use App\Http\Controllers\ChartOfAccountsExportController;
use App\Http\Controllers\DemoAuthController;
use App\Http\Controllers\ExpenseController;
use App\Http\Controllers\FinancialReportController;
use App\Http\Controllers\GeneralLedgerController;
use App\Http\Controllers\JournalEntryController;
use App\Http\Controllers\SalesRevenueController;
use App\Http\Controllers\TaxSettingController;
use Illuminate\Support\Facades\Route;

Route::redirect('/', '/login');

Route::get('/login', [DemoAuthController::class, 'show'])->name('login');
Route::post('/login', [DemoAuthController::class, 'login'])->name('login.attempt');
Route::get('/dashboard', [DemoAuthController::class, 'dashboard'])->name('dashboard');
Route::get('/chart-of-accounts', [DemoAuthController::class, 'chartOfAccounts'])->name('chart-of-accounts');
Route::post('/chart-of-accounts', [ChartOfAccountsController::class, 'store'])->middleware('demo.permission:configuration.manage')->name('chart-of-accounts.store');
Route::put('/chart-of-accounts/{code}', [ChartOfAccountsController::class, 'update'])->middleware('demo.permission:configuration.manage')->name('chart-of-accounts.update');
Route::patch('/chart-of-accounts/{code}/status', [ChartOfAccountsController::class, 'status'])->middleware('demo.permission:configuration.manage')->name('chart-of-accounts.status');
Route::delete('/chart-of-accounts/{code}', [ChartOfAccountsController::class, 'destroy'])->middleware('demo.permission:configuration.manage')->name('chart-of-accounts.destroy');
Route::get('/journal-entries', [JournalEntryController::class, 'index'])->name('journal-entries');
Route::get('/journal-entries/export/csv', [JournalEntryController::class, 'csv'])->name('journal-entries.export.csv');
Route::get('/journal-entries/export/pdf', [JournalEntryController::class, 'pdf'])->name('journal-entries.export.pdf');
Route::get('/journal-entries/{journalNumber}/print', [JournalEntryController::class, 'print'])->name('journal-entries.print');
Route::get('/journal-entries/{journalNumber}/pdf', [JournalEntryController::class, 'entryPdf'])->name('journal-entries.pdf');
Route::post('/journal-entries', [JournalEntryController::class, 'store'])->middleware('demo.permission:drafts.manage')->name('journal-entries.store');
Route::put('/journal-entries/{journalNumber}', [JournalEntryController::class, 'update'])->middleware('demo.permission:drafts.manage')->name('journal-entries.update');
Route::delete('/journal-entries/{journalNumber}', [JournalEntryController::class, 'destroy'])->middleware('demo.permission:drafts.manage')->name('journal-entries.destroy');
Route::post('/journal-entries/{journalNumber}/submit-review', [JournalEntryController::class, 'submitForReview'])->middleware('demo.permission:drafts.submit')->name('journal-entries.submit-review');
Route::post('/journal-entries/{journalNumber}/return-draft', [JournalEntryController::class, 'returnToDraft'])->middleware('demo.permission:transactions.approve')->name('journal-entries.return-draft');
Route::post('/journal-entries/{journalNumber}/post', [JournalEntryController::class, 'post'])->middleware('demo.permission:transactions.approve')->name('journal-entries.post');
Route::post('/journal-entries/{journalNumber}/reverse', [JournalEntryController::class, 'reverse'])->middleware('demo.permission:transactions.reverse')->name('journal-entries.reverse');
Route::get('/general-ledger', [GeneralLedgerController::class, 'index'])->name('general-ledger');
Route::get('/general-ledger/data', [GeneralLedgerController::class, 'data'])->name('general-ledger.data');
Route::get('/general-ledger/export/csv', [GeneralLedgerController::class, 'csv'])->name('general-ledger.export.csv');
Route::get('/general-ledger/export/pdf', [GeneralLedgerController::class, 'pdf'])->name('general-ledger.export.pdf');
Route::get('/sales-revenue', [SalesRevenueController::class, 'index'])->name('sales-revenue');
Route::post('/sales-revenue/customers', [SalesRevenueController::class, 'storeCustomer'])->middleware('demo.permission:master_data.manage')->name('sales-revenue.customers.store');
Route::post('/sales-revenue/invoices', [SalesRevenueController::class, 'storeInvoice'])->middleware('demo.permission:drafts.manage')->name('sales-revenue.invoices.store');
Route::post('/sales-revenue/invoices/{invoiceNumber}/post', [SalesRevenueController::class, 'postInvoice'])->middleware('demo.permission:transactions.approve')->name('sales-revenue.invoices.post');
Route::get('/sales-revenue/invoices/{invoiceNumber}/print', [SalesRevenueController::class, 'printInvoice'])->name('sales-revenue.invoices.print');
Route::get('/accounts-receivable', [AccountsReceivableController::class, 'index'])->name('accounts-receivable');
Route::post('/accounts-receivable/payments', [AccountsReceivableController::class, 'storePayment'])->middleware('demo.permission:drafts.manage')->name('accounts-receivable.payments.store');
Route::put('/accounts-receivable/payments/{receiptNumber}', [AccountsReceivableController::class, 'updatePayment'])->middleware('demo.permission:drafts.manage')->name('accounts-receivable.payments.update');
Route::delete('/accounts-receivable/payments/{receiptNumber}', [AccountsReceivableController::class, 'deletePayment'])->middleware('demo.permission:drafts.manage')->name('accounts-receivable.payments.destroy');
Route::post('/accounts-receivable/payments/{receiptNumber}/submit-review', [AccountsReceivableController::class, 'submitPaymentForReview'])->middleware('demo.permission:drafts.submit')->name('accounts-receivable.payments.submit-review');
Route::post('/accounts-receivable/payments/{receiptNumber}/return-draft', [AccountsReceivableController::class, 'returnPaymentToDraft'])->middleware('demo.permission:transactions.approve')->name('accounts-receivable.payments.return-draft');
Route::post('/accounts-receivable/payments/{receiptNumber}/post', [AccountsReceivableController::class, 'postPayment'])->middleware('demo.permission:transactions.approve')->name('accounts-receivable.payments.post');
Route::get('/accounts-receivable/export/csv', [AccountsReceivableController::class, 'csv'])->name('accounts-receivable.export.csv');
Route::get('/accounts-payable', [AccountsPayableController::class, 'index'])->name('accounts-payable');
Route::post('/accounts-payable/vendors', [AccountsPayableController::class, 'storeVendor'])->middleware('demo.permission:master_data.manage')->name('accounts-payable.vendors.store');
Route::put('/accounts-payable/vendors/{id}', [AccountsPayableController::class, 'updateVendor'])->middleware('demo.permission:master_data.manage')->name('accounts-payable.vendors.update');
Route::patch('/accounts-payable/vendors/{id}/status', [AccountsPayableController::class, 'vendorStatus'])->middleware('demo.permission:master_data.manage')->name('accounts-payable.vendors.status');
Route::post('/accounts-payable/bills', [AccountsPayableController::class, 'storeBill'])->middleware('demo.permission:drafts.manage')->name('accounts-payable.bills.store');
Route::put('/accounts-payable/bills/{billNumber}', [AccountsPayableController::class, 'updateBill'])->middleware('demo.permission:drafts.manage')->name('accounts-payable.bills.update');
Route::post('/accounts-payable/bills/{billNumber}/post', [AccountsPayableController::class, 'postBill'])->middleware('demo.permission:transactions.approve')->name('accounts-payable.bills.post');
Route::post('/accounts-payable/payments', [AccountsPayableController::class, 'storePayment'])->middleware('demo.permission:drafts.manage')->name('accounts-payable.payments.store');
Route::put('/accounts-payable/payments/{paymentNumber}', [AccountsPayableController::class, 'updatePayment'])->middleware('demo.permission:drafts.manage')->name('accounts-payable.payments.update');
Route::delete('/accounts-payable/payments/{paymentNumber}', [AccountsPayableController::class, 'deletePayment'])->middleware('demo.permission:drafts.manage')->name('accounts-payable.payments.destroy');
Route::post('/accounts-payable/payments/{paymentNumber}/submit-review', [AccountsPayableController::class, 'submitPaymentForReview'])->middleware('demo.permission:drafts.submit')->name('accounts-payable.payments.submit-review');
Route::post('/accounts-payable/payments/{paymentNumber}/return-draft', [AccountsPayableController::class, 'returnPaymentToDraft'])->middleware('demo.permission:transactions.approve')->name('accounts-payable.payments.return-draft');
Route::post('/accounts-payable/payments/{paymentNumber}/post', [AccountsPayableController::class, 'postPayment'])->middleware('demo.permission:transactions.approve')->name('accounts-payable.payments.post');
Route::get('/accounts-payable/export/csv', [AccountsPayableController::class, 'csv'])->name('accounts-payable.export.csv');
Route::get('/accounts-payable/export/pdf', [AccountsPayableController::class, 'pdf'])->name('accounts-payable.export.pdf');
Route::get('/cash-bank', [CashBankController::class, 'index'])->name('cash-bank');
Route::get('/cash-bank/export/csv', [CashBankController::class, 'csv'])->name('cash-bank.export.csv');
Route::post('/cash-bank/accounts', [CashBankController::class, 'storeAccount'])->middleware('demo.permission:cash_bank.manage')->name('cash-bank.accounts.store');
Route::put('/cash-bank/accounts/{code}', [CashBankController::class, 'updateAccount'])->middleware('demo.permission:cash_bank.manage')->name('cash-bank.accounts.update');
Route::patch('/cash-bank/accounts/{code}/status', [CashBankController::class, 'accountStatus'])->middleware('demo.permission:cash_bank.manage')->name('cash-bank.accounts.status');
Route::post('/cash-bank/accounts/{code}/adjust-balance', [CashBankController::class, 'adjustBalance'])->middleware('demo.permission:cash_bank.manage')->name('cash-bank.accounts.adjust');
Route::get('/cash-bank/accounts/{code}/activity', [CashBankController::class, 'activity'])->name('cash-bank.accounts.activity');
Route::post('/cash-bank/transactions', [CashBankController::class, 'storeTransaction'])->middleware('demo.permission:cash_bank.manage')->name('cash-bank.transactions.store');
Route::post('/cash-bank/transactions/{identifier}/reverse', [CashBankController::class, 'reverseTransaction'])->middleware('demo.permission:cash_bank.manage')->name('cash-bank.transactions.reverse');
Route::post('/cash-bank/reconciliations', [CashBankController::class, 'reconcile'])->middleware('demo.permission:cash_bank.manage')->name('cash-bank.reconciliations.store');
Route::get('/expenses', [ExpenseController::class, 'index'])->name('expenses');
Route::get('/expenses/export/csv', [ExpenseController::class, 'csv'])->name('expenses.export.csv');
Route::post('/expenses', [ExpenseController::class, 'store'])->middleware('demo.permission:drafts.manage')->name('expenses.store');
Route::put('/expenses/{expenseNumber}', [ExpenseController::class, 'update'])->middleware('demo.permission:drafts.manage')->name('expenses.update');
Route::post('/expenses/{expenseNumber}/submit-review', [ExpenseController::class, 'submitForReview'])->middleware('demo.permission:drafts.submit')->name('expenses.submit-review');
Route::post('/expenses/{expenseNumber}/approve', [ExpenseController::class, 'approve'])->middleware('demo.permission:transactions.approve')->name('expenses.approve');
Route::delete('/expenses/{expenseNumber}', [ExpenseController::class, 'destroy'])->middleware('demo.permission:drafts.manage')->name('expenses.destroy');
Route::get('/financial-reports', [FinancialReportController::class, 'index'])->name('financial-reports');
Route::get('/financial-reports/data', [FinancialReportController::class, 'data'])->name('financial-reports.data');
Route::get('/financial-reports/export/csv', [FinancialReportController::class, 'csv'])->name('financial-reports.export.csv');
Route::get('/tax-settings', [TaxSettingController::class, 'index'])->middleware('demo.permission:tax.manage')->name('tax-settings');
Route::get('/audit-trail', [AuditTrailController::class, 'index'])->middleware('demo.permission:audit.view')->name('audit-trail');
Route::get('/tax-settings/summary', [TaxSettingController::class, 'summary'])->middleware('demo.permission:tax.manage')->name('tax-settings.summary');
Route::get('/tax-settings/export/csv', [TaxSettingController::class, 'csv'])->middleware('demo.permission:tax.manage')->name('tax-settings.export.csv');
Route::post('/tax-settings', [TaxSettingController::class, 'store'])->middleware('demo.permission:tax.manage')->name('tax-settings.store');
Route::put('/tax-settings/{id}', [TaxSettingController::class, 'update'])->middleware('demo.permission:tax.manage')->name('tax-settings.update');
Route::patch('/tax-settings/{id}/status', [TaxSettingController::class, 'status'])->middleware('demo.permission:tax.manage')->name('tax-settings.status');
Route::post('/tax-settings/{id}/default', [TaxSettingController::class, 'setDefault'])->middleware('demo.permission:tax.manage')->name('tax-settings.default');
Route::get('/chart-of-accounts/export/pdf', [ChartOfAccountsExportController::class, 'pdf'])->name('chart-of-accounts.export.pdf');
Route::get('/chart-of-accounts/export/csv', [ChartOfAccountsExportController::class, 'csv'])->name('chart-of-accounts.export.csv');
Route::post('/logout', [DemoAuthController::class, 'logout'])->name('logout');
